### ISSUE TITLE
SAE Tabs on AE Page

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/aeexplorer#3]
Basically what is needed here is a way to prominently see and sort on SAEs (not simply embedded within AEs)
o	Simple line listing would usually do
o	Specific instruction to include SAEs as well as AEs
 
Also good would be to have a way (on the graphics site) to see which were SAEs
•	line listing of SAEs (i.e., not necessarily differentiating AEs from SAEs within AE tables or graphs)
•	 some kind of highlighting of SAEs within the graph. 
•	being able to see SAEs graphically along with the others and a way of filtering to see just the SAEs

**Comment by jwildfire** [comment]
We can certainly add an "SAE" filter to the existing chart. Not sure if that is sufficient, of it the request above is for a new chart type. @brittsikora What do you think? Should we follow up with, Jack?

**Comment by brittsikora** [comment]
Followed up with Jack:

"Note that the current dropdowns on the AE Table between “Filter by Prevalence” and “Category” contain “AE Serious” to select whether or not you want the SAEs to show.  But what is also needed is a way to have ONLY the SAEs show (i.e., SAEs and not the non-SAE AEs).  But since %ages won’t be very helpful for those (since they’re generally few and scattered across organ systems), what I was saying is that a simple line listing to see the SAEs would do.  But if it’s easier to have them populate the chart the way AEs (and AEs + SAEs) currently do, I think that’s ok too.  I’ll also need to be able to see the SAEs on the AE Timeline page.  I’m not sure they currently show there – or at least there’s no dropdown to select for them.  The Timeline dropdowns, like the AE Table dropdowns, should include something to select for SAEs alone.

So what this is proposing, which would be helpful is:  A line listing of SAEs, a color coding of SAEs in the AE Timeline that differentiates them from AEs (which I think currently use green, yellow, and red; so maybe purple or something), and a way in the AE Table and Timelines to filter on just SAEs (as noted above)."

**Comment by jwildfire** [comment]
@brittsikora So, there are a few different things here. 

>  A line listing of SAEs

We could implement this by making the total row at the bottom of the chart clickable. Created a new issue #16 for this. 

>  ... a color coding of SAEs in the AE Timeline that differentiates them from AEs (which I think currently use green, yellow, and red; so maybe purple or something)

Probably best to leave the colors as they are, but we could encode "serious" in the chart in a different way. Maybe plot those with an X (or an S) instead of a circle. Created a new [issue](https://github.com/RhoInc/ae-timelines/issues/19) in the ae-timeline repo. 

> ... a way in the AE Table and Timelines to filter on just SAEs (as noted above).

<img width="1176" alt="screen shot 2016-06-30 at 7 50 24 pm" src="https://cloud.githubusercontent.com/assets/3680095/16507932/f2854e4e-3efb-11e6-83c2-2d62e52b5196.png">
way in the AE Table and Timelines to filter on just SAEs 

You can subset the current display to show only SAEs using the serious AE filter, as shown in the screenshot above. That isn't there by default in the AE Timeline but it's trivial to add. @brittsikora can you confirm that this behaviour is ok as is, and, if so, close this issue. We may need to make a new issue in chart-foundry-rho to add a filter for SAEs in the timeline.

**Comment by brittsikora** [comment]
I would say that that's fine for now and we should add an issue for the SAE filter in the CF-Rho board. If that's fine with you, I'll make that issue and close this one

**Comment by jwildfire** [comment]
@brittsikora perfect. go for it.
