### ISSUE TITLE
Allow filters on participant characteristics

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/aeexplorer#4]
Filter by subgroup, (sex, median age split, and active vs. placebo when unblinded)

**Comment by jwildfire** [comment]
Adding participant-level filters on the primary page is possible (see http://graphics.rhoworld.com/tools/aeexplorer/example4/), but complicated. The most robust way to handle it is to have two separate data inputs for the chart. One event-level data set for AEs and one participant-level data set for demographics. Would break backwards compatibility, but will consider for version 3. 

Other options are possible, but are going to involve complex settings for filters, which I want to avoid.

**Comment by jwildfire** [comment]
I'm leaning towards adding a `type` parameter to filter specifications instead of requiring multiple files. Options for type are:
- 'event' for filters related to the AEs themselves, like event Severity (this is the currently supported functionality)
- 'participant' for filters related to the participants, like participant Gender (not currently supported)

The new specification would look like this: 

```
filters:  [   
  {'value_col': 'AESER'
  ,'label': 'Serious?'
  ,'type':'event'} //new in v3.0.0
  ,{'value_col': 'GENDER'
  ,'label': 'Gender'
  ,'type':'participant'}] //new in v3.0.0
```

I *think* code changes would be isolated to the following files:  
- /src/chart/AETable/util/prepareData.js - Changes to the algorithm chart.filtered_data (this would represent the bulk of the edits
- /src/chart/AETable/controls/custom/init.js - Add a label to each filter showing the type
- /src/chart/defaultSettings.js - update filter defaults to include `type`

I'll start on a branch off of `refactor` with this approach and see how it goes.

**Comment by jwildfire** [comment]
Seems like approach above will work well. Initial commit branch [`v3-filters`](https://github.com/RhoInc/aeexplorer/tree/v3-filters)

**Comment by jwildfire** [comment]
@samussiah can you QC/Code review this little bit of the refactor please? See #4 for details. Example [here](http://bl.ocks.org/jwildfire/c5355b066da3c81de480f73876860eb9)

**Comment by jwildfire** [comment]
merged in to `refactor` will be released in v3
